version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.14.2
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
        networks:
            - elknetwork
    kibana:
        image: kibana:7.14.2
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        networks:
            - elknetwork
    logstash:
        image: logstash:7.14.2
        container_name: logstash
        hostname: logstash
        volumes:
            - /home/debian/pipeline/:/usr/share/logstash/pipeline
            - ~/postgresql-42.3.1.jar:/usr/share/logstash/vendor/jar/jdbc/postgresql-42.3.1.jar
            - /home/debian/pipelines.yml:/usr/share/logstash/config/pipelines.yml
        ports:
            - 9600:9600
        depends_on:
            - elasticsearch
        networks:    
            - elknetwork
networks:
    elknetwork:
        driver: bridge
